name: os-csem

channels:
  - defaults
  - conda-forge
dependencies:
  - discretize
  - emg3d
  - empymod
  - h5netcdf
  - ipython
  - jupyter
  - matplotlib
  - mkl
  - numba
  - numpy
  - python>=3.6
  - scipy
  - scooby
  - xarray
