name: csem

channels:
  - conda-forge
  - gimli
  - defaults
dependencies:
  - custem
  - discretize
  - emg3d
  - h5netcdf
  - ipython
  - jupyter
  - matplotlib
  - memory_profiler
  - mkl
  - python>=3.6
  - scooby
  - segyio
  - xarray
