name: csem

channels:
  - defaults
  - conda-forge
  - gimli
dependencies:
  - custem
  - discretize
  - emg3d
  - empymod
  - h5netcdf
  - ipython
  - jupyter
  - matplotlib
  - memory_profiler
  - mkl
  - numba
  - numpy
  - python>=3.6
  - scipy
  - scooby
  - xarray
