###############################################################################
# PETGEM parameters file
###############################################################################
# Model parameters
model:
  mesh_file: marlim.vtk      # Mesh file (vtk format v2)
  basis_order: 2                        # Vector basis order (1,2,3,4,5,6)
  frequency: [0.125, 0.25, 0.5, 0.75, 1., 1.25]                        # Frequency
  src_position: [0., 0., 0.]            # This information is provided by modify_marlim_input_data.py and used in run_preprocessing.py
  src_azimuth: 0                        # Source rotation in xy plane
  src_dip: 0                            # Source rotation in xz plane
  src_current: 1.                     # Source current
  src_length: 10.                      # Source length
  # Comment/uncomment the following lines as appropriate
  # Conductivity values for block model
  sigma_horizontal: None   # Horizontal conductivity for each material (This information is provided by modify_marlim_input_data.py and used in run_preprocessing.py)
  sigma_vertical: None     # Vertical conductivity for each material (This information is provided by modify_marlim_input_data.py and used in run_preprocessing.py)
  # Conductivity values for layered model
  #sigma_horizontal: [.00000001, 3.3333, 1., 0.5, .001, .5, .5, .5]   # Horizontal conductivity for each material
  #sigma_vertical: [.00000001, 3.3333, 1., .25, .001, .25, .25, .25]  # Vertical conductivity for each material
  # Please uncomment the following line if a file with the conductivity model is provided.
  # (1 row per element and 2 conductivity values per row (sigma_horizontal and sigma_vertical))
  # If sigma_file is provided, sigma_horizontal and sigma_vertical are ignored
  sigma_file: None           # This information is provided by modify_marlim_input_data.py and used in run_preprocessing.py
  receivers_file: None       # This information is provided by modify_marlim_input_data.py and used in run_preprocessing.py

# Execution parameters
run:
  cuda: False                           # Flag to activate/deactivate cuda support

# Output parameters
output:
  directory: out               # Directory for output (results)
  directory_scratch: tmp       # Directory for temporal files
